server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_login?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
jwt:
  jwtSec: chao #密钥
